services:
  # 1. SERVICIO K6: El generador de carga
  # docker-compose.yml (Sección k6)
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./script.js:/script.js:ro
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:3030/api/v1/write
      K6_PROMETHEUS_RW_TREND_STATS: 'p(90),p(95),p(99),avg,min,max'
      K6_PROMETHEUS_RW_PUSH_INTERVAL: 1s
    depends_on:
      - prometheus
    networks:
      - k6-net
    entrypoint: /bin/sh
    command: -c "tail -f /dev/null"

  # 2. SERVICIO PROMETHEUS: Almacena las métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - "3030:9090"
    networks:
      - k6-net

  # 3. SERVICIO GRAFANA: Visualiza los resultados
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - k6-net

volumes:
  grafana-data:

networks:
  k6-net:
    driver: bridge
