global:
  resolve_timeout: 5s

route:
  receiver: 'autoscaler'
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m

receivers:
- name: 'autoscaler'
  webhook_configs:
  - url: 'http://autoscaler:5000/alert'
    send_resolved: false